-- MySQL Script generated by MySQL Workbench
-- 08/02/16 15:37:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Personas` (
  `perCi` INT NOT NULL COMMENT 'Cedula de Identidad de la Persona.\n',
  `perNombre` VARCHAR(45) NOT NULL COMMENT 'Nombre de la Persona\n',
  `perSNombre` VARCHAR(45) NULL COMMENT 'Segundo Nombre de la Persona',
  `perApellido` VARCHAR(45) NOT NULL COMMENT 'Apellido de la Persona',
  `perSApellido` VARCHAR(45) NULL COMMENT 'Segundo Apellido de la Persona',
  `perFchNac` DATETIME NOT NULL COMMENT 'Fecha de Nacimiento de la Persona\n\n',
  `perSexo` TINYINT(1) NOT NULL COMMENT 'Sexo de la Persona \n0 - Mujer\n1 - Hombre\n',
  `perUser` VARCHAR(8) NULL COMMENT 'Nombre de Usuario de Persona\nMax. 8 caracteres\n',
  PRIMARY KEY (`perCi`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paises` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Paises` (
  `paisCod` INT NOT NULL COMMENT 'Codigo del País\n',
  `paisNombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del Pais\n',
  `paisFchBaja` DATE NULL COMMENT 'Fecha de Baja del Pais\n',
  PRIMARY KEY (`paisCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ciudades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ciudades` (
  `ciuCod` INT NOT NULL COMMENT 'Código de la Ciudad\n',
  `ciuNom` VARCHAR(45) NULL COMMENT 'Nombre de la Ciudad\n',
  `paisCod` INT NOT NULL COMMENT 'Pais a cual pertenece la Ciudad\n',
  `ciuFchBaja` DATETIME NULL COMMENT 'Fecha de Baja\n',
  PRIMARY KEY (`ciuCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Calles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Calles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Calles` (
  `callCod` INT NOT NULL COMMENT 'Id de la Calle\n',
  `CallDir` VARCHAR(45) NOT NULL COMMENT 'Nombre de la Calle\n',
  `ciuCod` INT NOT NULL COMMENT 'Id de la Ciudad\n',
  `callFchBaja` DATETIME NULL COMMENT 'Fecha de Baja de la Calle\n',
  PRIMARY KEY (`callCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `perCi` INT NOT NULL,
  PRIMARY KEY (`perCi`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clientes` (
  `perCi` INT NOT NULL COMMENT 'Cedula de Identidad del Cliente\n',
  PRIMARY KEY (`perCi`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administradores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Administradores` (
  `perCi` INT NOT NULL COMMENT 'Cedula de Identidad de los Administradores\n',
  PRIMARY KEY (`perCi`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categorias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Categorias` (
  `catCod` INT NOT NULL COMMENT 'Código de la Categoría',
  `catNom` VARCHAR(45) NOT NULL COMMENT 'Nombre de la Categoría\n',
  `catDesc` VARCHAR(45) NULL COMMENT 'Descripción de la Categoría\n',
  `catFchBaja` DATETIME NULL COMMENT 'Fecha de Baja de la Categoría\n',
  PRIMARY KEY (`catCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Premios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Premios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Premios` (
  `preCod` INT NOT NULL COMMENT 'Código del Premio\n',
  `preNombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del Premio\n',
  `preDesc` VARCHAR(45) NULL COMMENT 'Descripción del Premio\n',
  `preFchBaja` DATETIME NULL COMMENT 'Fecha de Baja del Premio\n',
  `catCod` INT NULL,
  PRIMARY KEY (`preCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Comercios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comercios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Comercios` (
  `comCod` INT NOT NULL COMMENT 'Código del Comercio\n',
  `comNom` VARCHAR(45) NULL COMMENT 'Nombre del Comercio\n',
  PRIMARY KEY (`comCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Sucursales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sucursales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Sucursales` (
  `sucCod` INT NOT NULL COMMENT 'Código de la Sucursal\n',
  `sucNom` VARCHAR(45) NULL COMMENT 'Nombre de la Sucursal\n',
  `comCod` INT NULL COMMENT 'Codigo del Comercio\n',
  PRIMARY KEY (`sucCod`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
